BACKUP LOG [AdventureWorks2025] TO  DISK = N'C:\SQL_BACKUPS\AdventureWorks2025_01trm' WITH NOFORMAT, NOINIT,  NAME = N'AdventureWorks2025-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO
