BACKUP DATABASE [AdventureWorks2025] TO  DISK = N'C:\SQL_BACKUPS\AdventureWorks2025_diff.diff' WITH  DIFFERENTIAL , NOFORMAT, NOINIT,  NAME = N'AdventureWorks2025-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO
