BACKUP DATABASE [AdventureWorks2025] TO  DISK = N'C:\SQL_BACKUPS\AdventureWorks2025_diff_1.diff' WITH  DIFFERENTIAL , 
NOFORMAT, NOINIT,  NAME = N'AdventureWorks2025-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO


USE [master]
RESTORE DATABASE [AdventureWorks2025] FROM DISK = N'C:\SQL_BACKUPS\AdventureWorks2025_full.BAK' WITH FILE = 1, NORECOVERY, NOUNLOAD, STATS = 5
GO 


USE [master]
RESTORE DATABASE [AdventureWorks2025] FROM DISK = N'C:\SQL_BACKUPS\AdventureWorks2025_diff_1.diff' WITH FILE = 1, NORECOVERY, NOUNLOAD, STATS = 5
GO 

RESTORE DATABASE AdventureWorks2025 WITH RECOVERY 
GO 
