"""empty message

Revision ID: 742880ff61ad
Revises: a05fbac9ed7f
Create Date: 2026-09-08 10:12:26.106435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742880ff61ad'
down_revision = 'a05fbac9ed7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
