name: Database Deployment

on:
  push:
    branches:
      - main
      - staging

  workflow_dispatch:

jobs:

  deploy-database:
    runs-on: windows-latest

    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'Buhle' }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Determine Environment
        id: env
        shell: powershell
        run: |
          if ("${{ github.ref_name }}" -eq "main") {
            echo "ENV_NAME=production" >> $env:GITHUB_OUTPUT
          } else {
            echo "ENV_NAME=Buhle" >> $env:GITHUB_OUTPUT
          }

      - name: Send Approval Request Notification (Teams)
        shell: powershell
        run: |
          $payload = @{
            text = "APPROVAL REQUIRED `nBranch: ${{ github.ref_name }}`nEnvironment: ${{ steps.env.outputs.ENV_NAME }}`nPlease approve in GitHub Environments"
          } | ConvertTo-Json

          Invoke-RestMethod `
            -Uri "${{ secrets.TEAMS_WEBHOOK_URL }}" `
            -Method Post `
            -Body $payload `
            -ContentType "application/json"

      - name: Debug Connection
        shell: powershell
        run: |
          Write-Host "Branch: ${{ github.ref_name }}"
          Write-Host "Environment: ${{ steps.env.outputs.ENV_NAME }}"
          Write-Host "Server: ${{ secrets.PROJECT_URL }}"
          Write-Host "Database: ${{ secrets.DATABASE_NAME }}"

      - name: Execute SQL Deployment
        shell: powershell
        run: |
          sqlcmd `
            -S "${{ secrets.PROJECT_URL }}" `
            -d "${{ secrets.DATABASE_NAME }}" `
            -U "${{ secrets.USER_NAME }}" `
            -P "${{ secrets.PASSWORD_SQL }}" `
            -C `
            -b `
            -i "SQL Project/deploy.sql"

      - name: Notify Success
        if: success()
        shell: powershell
        run: |
          $payload = @{
            text = "SUCCESS `nBranch: ${{ github.ref_name }}`nEnvironment: ${{ steps.env.outputs.ENV_NAME }}"
          } | ConvertTo-Json

          Invoke-RestMethod `
            -Uri "${{ secrets.TEAMS_WEBHOOK_URL }}" `
            -Method Post `
            -Body $payload `
            -ContentType "application/json"

      - name: Notify Failure
        if: failure()
        shell: powershell
        run: |
          $payload = @{
            text = "FAILED `nBranch: ${{ github.ref_name }}`nEnvironment: ${{ steps.env.outputs.ENV_NAME }}"
          } | ConvertTo-Json

          Invoke-RestMethod `
            -Uri "${{ secrets.TEAMS_WEBHOOK_URL }}" `
            -Method Post `
            -Body $payload `
            -ContentType "application/json"
