name: Database Deployment Template

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string

jobs:

  deploy:
    runs-on: windows-latest

    environment:
      name: ${{ inputs.environment_name }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Notify Deployment Started
        shell: powershell
        run: |
          $timestamp = Get-Date -Format "yyyy-MM-dd"

          $text = "DATABASE DEPLOYMENT - STARTED`n`nCreator: ${{ github.actor }}`n`nEnvironment: ${{ inputs.environment_name }}`n`nDate: $timestamp`n`nDeployment has started."

          $payload = @{ text = $text } | ConvertTo-Json -Depth 1

          Invoke-RestMethod `
            -Uri "${{ secrets.TEAMS_WEBHOOK_URL }}" `
            -Method Post `
            -Body $payload `
            -ContentType "application/json"

      - name: Execute SQL Script
        shell: powershell
        run: |
          sqlcmd `
            -S "${{ secrets.PROJECT_URL }}" `
            -d "master" `
            -U "${{ secrets.USER_NAME }}" `
            -P "${{ secrets.PASSWORD_SQL }}" `
            -C `
            -b `
            -i "SQL Project/deploy.sql"

      - name: Notify Success
        if: success()
        shell: powershell
        run: |
          $timestamp = Get-Date -Format "yyyy-MM-dd"

          $text = "DATABASE DEPLOYMENT - SUCCESS`n`nCreator: ${{ github.actor }}`n`nEnvironment: ${{ inputs.environment_name }}`n`nDate: $timestamp`n`nDeployment completed successfully."

          $payload = @{ text = $text } | ConvertTo-Json -Depth 1

          Invoke-RestMethod `
            -Uri "${{ secrets.TEAMS_WEBHOOK_URL }}" `
            -Method Post `
            -Body $payload `
            -ContentType "application/json"

      - name: Notify Failure
        if: failure()
        shell: powershell
        run: |
          $timestamp = Get-Date -Format "yyyy-MM-dd"

          $text = "DATABASE DEPLOYMENT - FAILED`n`nCreator: ${{ github.actor }}`n`nEnvironment: ${{ inputs.environment_name }}`n`nDate: $timestamp`n`nDeployment failed. Please review logs."

          $payload = @{ text = $text } | ConvertTo-Json -Depth 1

          Invoke-RestMethod `
            -Uri "${{ secrets.TEAMS_WEBHOOK_URL }}" `
            -Method Post `
            -Body $payload `
            -ContentType "application/json"
