on:
  workflow_dispatch: # Allows you to manually trigger the deployment from the GitHub Actions tab.
  push:
    branches:
      - main       # Triggers automatically when changes are pushed to the main branch.
 
jobs:
  deploy-database:
    runs-on: windows-latest
 
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        
      - name: Execute SQL Script
        shell: powershell
        run: |
          sqlcmd `
            -S "${{ secrets.PROJECT_URL }}" `
            -d "${{ secrets.DATABASE_NAME }}" `
            -U "${{ secrets.USER_NAME }}" `
            -P "${{ secrets.PASSWORD_SQL }}" `
            -C `
            -i "SQL Project/deploy.sql"
