name: Database Deployment

on:
  push:
    branches:
      - main
      - staging

  workflow_dispatch:

jobs:

  deploy-database:
    runs-on: windows-latest

    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'Buhle' }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Determine Environment
        id: env
        shell: powershell
        run: |
          if ("${{ github.ref_name }}" -eq "main") {
            echo "ENV_NAME=production" >> $env:GITHUB_OUTPUT
          } else {
            echo "ENV_NAME=Buhle" >> $env:GITHUB_OUTPUT
          }

      #  ONLY RUNS ON STAGING NOW
      - name: Send Approval Request Notification (Teams)
        if: github.ref_name == 'staging'
        shell: powershell
        run: |
          $envName = "${{ steps.env.outputs.ENV_NAME }}"

          $payload = @{
            text = " DATABASE DEPLOYMENT APPROVAL REQUIRED`n`n Requested by: Shriya`n Branch: ${{ github.ref_name }}`n Environment: $envName`n Time: $(Get-Date)`n`n Action Required: Please approve this deployment in GitHub Environments."
          } | ConvertTo-Json

          Invoke-RestMethod `
            -Uri "${{ secrets.TEAMS_WEBHOOK_URL }}" `
            -Method Post `
            -Body $payload `
            -ContentType "application/json"

      - name: Execute SQL Script
        shell: powershell
        run: |
          sqlcmd `
            -S "${{ secrets.PROJECT_URL }}" `
            -d "master" `
            -U "${{ secrets.USER_NAME }}" `
            -P "${{ secrets.PASSWORD_SQL }}" `
            -C `
            -i "SQL Project/deploy.sql"

      - name: Notify Success
        if: success()
        shell: powershell
        run: |
          $envName = "${{ steps.env.outputs.ENV_NAME }}"

          $payload = @{
            text = " DEPLOYMENT SUCCESSFUL`n`n Deployed by: Shriya`n Branch: ${{ github.ref_name }}`n Environment: $envName`n Time: $(Get-Date)`n`n Database deployed successfully."
          } | ConvertTo-Json

          Invoke-RestMethod `
            -Uri "${{ secrets.TEAMS_WEBHOOK_URL }}" `
            -Method Post `
            -Body $payload `
            -ContentType "application/json"

      - name: Notify Failure
        if: failure()
        shell: powershell
        run: |
          $envName = "${{ steps.env.outputs.ENV_NAME }}"

          $payload = @{
            text = " DEPLOYMENT FAILED`n`n Triggered by: Shriya`n Branch: ${{ github.ref_name }}`n Environment: $envName`n Time: $(Get-Date)`n`n Please check GitHub Actions logs for error details."
          } | ConvertTo-Json

          Invoke-RestMethod `
            -Uri "${{ secrets.TEAMS_WEBHOOK_URL }}" `
            -Method Post `
            -Body $payload `
            -ContentType "application/json"
